version: '3'

services:
  debhernandezmysql:
    build:
      context: .
      dockerfile: Dockerfile
    image: debhernandezmysql
    container_name: debhernandezmysql
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - "10300:8080"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    depends_on:
      - mysql
    command: ./wait-for.sh pedromysql:3306 -- /home/node/app/node_modules/.bin/nodemon app.js

  mysql:
    image: mysql:latest
    container_name: pedromysql  # Corrección: Nombre del contenedor debe ser diferente
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    volumes:
      - mysqldata:/var/lib/pedromysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysqldata:
  node_modules:
